'format':
    'filename': 'ODC._%Y%m%d%H%M.nc'
    'fileformat': 'netCDF'
'vars':
    'refl':
        'var_raw': 'dataset1:data1:data'
        'postprocess': True
        'res': '2 km'
        'FSS': 
            'thresholds': [10, 20, 30, 40, 50]
            'scales': [4, 6, 8, 10, 12, 14]
        'SAL':
            'f': 0.50
            'q': 0.95
            'tstorm_kwargs': {"max_num_features": None, "minref": 35, "maxref": 48, "mindiff": 6, "minsize": 50, "minmax": 41, "mindis": 10}
    'pcp':
        'var': 'dataset1:data1:data'
        'postprocess': True
        'res': '2 km'
        'description': '1-hour Accumulated Precipitation'
        'units': 'mm'
        'FSS': 
            'thresholds': [1, 3, 5, 10, 15]
            'scales': [4, 6, 8, 10, 12, 14]
        'SAL':
            'f': 1.0
            'q': 0.97
            'tstorm_kwargs': {"max_num_features": None, "minref": 35, "maxref": 48, "mindiff": 6, "minsize": 50, "minmax": 41, "mindis": 10}