'format':
    'filename': '3B-HHR-L.MS.MRG.3IMERG.%Y%m%d-%H_%M.V06B.nc'
    'fileformat': 'netCDF'
'vars':
    'pcp':
        'var': 'precipitationCal'
        'postprocess': True
        'res': '0.1 ยบ'
        'description': '1-hour Accumulated Precipitation'
        'units': 'mm'
        'FSS': 
            'thresholds': [1, 5, 10, 15, 20]
            'scales': [2, 3, 4, 5, 6, 7]
        'SAL':
            'f': 0.50
            'q': 0.95
            'tstorm_kwargs': {"max_num_features": None, "minref": 35, "maxref": 48, "mindiff": 6, "minsize": 14, "minmax": 41, "mindis": 10}
