'path':
    '/path/to/downloaded/observations'
'format':
    'filename':
        '': ''
    'fileformat': ''
'vars':
    '':
        'var': ''
        'postprocess': 
        'res': ''
	'description': ''
	'units': ''
        'FSS': 
            'thresholds': []
            'scales': []
        'SAL':
            'f': 
            'q': 
            'tstorm_kwargs': {"max_num_features": , "minref": , "maxref": , "mindiff": , "minsize": , "minmax": , "mindis": }

